### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ice987987** [ice987987/ioBroker.hagelschutz#122]
### The problem

@iobroker-bot recheck

### Version of Node.js

x

### Version of ioBroker js-controller

x

### Version of "hagelschutz"-adapter

x

### Version of "admin"-adapter

x

### Operating system incl. version running ioBroker

x

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode and check that there are no personal information)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by mcm1957** [comment]
@iobroker-bot recheck
