### ISSUE TITLE
Simple True/False flag for Hail

### ISSUE THREAD

**Issue by phifogg** [ice987987/ioBroker.hagelschutz#92]
### Feature or idea description

The idea is to use the hail-state to open window blinds. I am using Shuttercontrol for my blinds which needs a simple true/false for alarm states. Right now I need to calculate that based on the result coming in via this adapter. Avoiding an extra script would be great.

Thanks for creating this adapter! It was on my list for long time but never had the chance to :D

### Version of "hagelschutz"-adapter

0.0.6

**Comment by ice987987** [comment]
please check 0.0.7-beta.1
